name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
            java-version: 18
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Build
        run: mvn install && mvn clean package
      - name: Push to cdn
        uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./target
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com