name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
            java-version: 18
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Build
        run: mvn install && mvn clean package
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Push to cdn
        uses: ptienchuan/deploy-github-pages-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}